# Generated by Django 4.2.13 on 2024-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Master',
            fields=[
                ('TransId', models.AutoField(primary_key=True, serialize=False)),
                ('E_Mail', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=500)),
                ('BusinessName', models.CharField(max_length=200)),
                ('BUsinessLocation', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('TransId', models.AutoField(primary_key=True, serialize=False)),
                ('E_Mail', models.EmailField(max_length=100)),
                ('VerifyOTP', models.IntegerField(max_length=6)),
                ('Status', models.CharField(default='N', max_length=1)),
                ('EntryTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
